<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.danmakulive</groupId>
    <artifactId>danmakulive-gatling</artifactId>
    <version>0.1.0</version>
    <packaging>jar</packaging>

    <properties>
        <gatling.version>3.10.5</gatling.version>
        <gatling-maven-plugin.version>4.8.2</gatling-maven-plugin.version>
        <scala.version>2.13.12</scala.version>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.gatling.highcharts</groupId>
            <artifactId>gatling-charts-highcharts</artifactId>
            <version>${gatling.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>io.gatling</groupId>
                <artifactId>gatling-maven-plugin</artifactId>
                <version>${gatling-maven-plugin.version}</version>
                <configuration>
                    <simulationsFolder>src/test/scala</simulationsFolder>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
